version: "3.11"

services:
   postgres:
      image: postgres:15-alpine
      restart: always
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}

   redis:
      image: redis:6-alpine
      restart: always
      env_file: .env
      command: redis-server
      ports:
         - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
         - "${REDIS_PORT}"
      volumes:
         - redis-data:/redis_data

volumes:
   postgres-data:
   redis-data: