"""tasks

Revision ID: 1070262d1e56
Revises: 88579d75cea2
Create Date: 2024-06-27 19:09:07.143074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1070262d1e56"
down_revision: Union[str, None] = "88579d75cea2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("price_rub", sa.DECIMAL(precision=1000, scale=3), nullable=False),
        sa.Column("price_uzs", sa.DECIMAL(precision=1000, scale=3), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "association_table",
        sa.Column("users_id", sa.Integer(), nullable=True),
        sa.Column("tasks_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tasks_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["users.id"],
        ),
    )
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.NUMERIC(precision=100, scale=3),
        type_=sa.DECIMAL(precision=1000, scale=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.DECIMAL(precision=1000, scale=3),
        type_=sa.NUMERIC(precision=100, scale=3),
        existing_nullable=False,
    )
    op.drop_table("association_table")
    op.drop_table("tasks")
    # ### end Alembic commands ###
