"""init

Revision ID: 88579d75cea2
Revises: 
Create Date: 2024-06-27 01:08:30.503313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88579d75cea2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("locale", sa.String(length=2), nullable=True),
        sa.Column("notifications", sa.Boolean(), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=100, scale=3), nullable=False),
        sa.Column(
            "currency", sa.Enum("RUB", "UZS", name="currencytype"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.drop_index(
        "ethereum_key_value_store_key_idx",
        table_name="ethereum_key_value_store",
        postgresql_using="hash",
    )
    op.drop_table("ethereum_key_value_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ethereum_key_value_store",
        sa.Column("key", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column("value", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("key", name="ethereum_key_value_store_pkey"),
    )
    op.create_index(
        "ethereum_key_value_store_key_idx",
        "ethereum_key_value_store",
        ["key"],
        unique=False,
        postgresql_using="hash",
    )
    op.drop_table("users")
    # ### end Alembic commands ###
